name: Build Windows EXE and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and release EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole gui.py
          mkdir dist_release
          move dist\gui.exe dist_release\AutoActivityScheduler.exe

      - name: Create ZIP file
        run: |
          powershell Compress-Archive -Path dist_release\* -DestinationPath AutoActivityScheduler.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist_release/AutoActivityScheduler.exe
            AutoActivityScheduler.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
